services:
  migrator:
    env_file: []
    environment:
      DATABASE_URL: ${DATABASE_URL}

  seeder:
    env_file: []
    environment:
      DATABASE_URL: ${DATABASE_URL}

  app:
    env_file: []
    environment:
      DATABASE_URL: ${DATABASE_URL}
      AUTH_SECRET: ${AUTH_SECRET}
      SECRET_KEY: ${SECRET_KEY}
      BETTER_AUTH_URL: ${BETTER_AUTH_URL}
      NEXT_PUBLIC_BETTER_AUTH_URL: ${BETTER_AUTH_URL}
      NEXT_PUBLIC_PORTAL_URL: ${BETTER_AUTH_URL_PORTAL}
      BETTER_AUTH_SECRET: ${BETTER_AUTH_SECRET}
      RESEND_API_KEY: ${RESEND_API_KEY}
      TRIGGER_SECRET_KEY: ${TRIGGER_SECRET_KEY}
      REVALIDATION_SECRET: ${REVALIDATION_SECRET}
      OPENAI_API_KEY: ${OPENAI_API_KEY}

  portal:
    env_file: []
    environment:
      DATABASE_URL: ${DATABASE_URL}
      BETTER_AUTH_SECRET: ${BETTER_AUTH_SECRET}
      BETTER_AUTH_URL: ${BETTER_AUTH_URL_PORTAL}
      NEXT_PUBLIC_BETTER_AUTH_URL: ${BETTER_AUTH_URL_PORTAL}
      RESEND_API_KEY: ${RESEND_API_KEY}